(* ::Package:: *)

(* ::Input:: *)
(*EccentricAnomaly[ma_,e_,\[Epsilon]_,countMax_,ini_]:= *)
(*Module[*)
(*{xOld=ma+1000,x=ma,count=0,x1,x2},*)
(*While[Abs[x-xOld]>\[Epsilon]&& count<countMax,*)
(*xOld=x;*)
(*If[count<ini,*)
(*x1=ma+e*Sin@x; x2=ma+e*Sin@x1;x=(x1+x2)*0.5,*)
(*x+=(ma-x+e*Sin@x)/(1.-e*Cos@x)];*)
(*count++];*)
(*x];*)
(**)
(*KeplerianToCartesian[a_,e_,\[Omega]_,\[CapitalOmega]_,i_,M_,t_]:=*)
(*Module[*)
(*{\[Mu],Mt,EA,\[Nu],rct,opos,ovel,rpos,rvel},*)
(*\[Mu]=1.32709742648*10^20(*GetSIBaseValue@"EarthMass"*GetSIBaseValue@"GravitationalConstant"*);*)
(*Mt=Mod[M+t Sqrt[\[Mu]/a^3],2Pi];*)
(*EA=EccentricAnomaly[Mt,e,10^-5,200,2];*)
(*\[Nu]=2ArcTan[Sqrt[(1+e)/(1-e)]Tan[EA/2]]+2Pi;*)
(*rct=a(1-e Cos@EA);*)
(*opos=rct{Cos@\[Nu],Sin@\[Nu],0};*)
(*(*ovel=(Sqrt[\[Mu] a]/rct){-Sin@EA,Sqrt[1-e^2]Cos@EA,0};*)*)
(*rpos=RotationMatrix[\[CapitalOmega],{0,0,1}].RotationMatrix[i,{1,0,0}].RotationMatrix[\[Omega],{0,0,1}].opos;*)
(*rpos];*)
