(* ::Package:: *)

(* ::Input:: *)
(*GetSIBaseValue[constant_]:=QuantityMagnitude[UnitConvert[Quantity[constant],"SIBase"]];*)
(*PlanetList={"Mercury","Venus","Earth","Mars","Jupiter","Saturn","Uranus","Neptune"};*)
(*GetCelestialData[celestialName_]:=*)
(*{celestialName,*)
(*PlanetData[celestialName, "Color"],*)
(*GetSIBaseValue@PlanetData[celestialName, "Radius"],*)
(*GetSIBaseValue@PlanetData[celestialName,"Mass"]*GetSIBaseValue@"GravitationalConstant",*)
(*GetSIBaseValue@PlanetData[celestialName,"SemimajorAxis"],*)
(*PlanetData[celestialName,"Eccentricity"],*)
(*GetSIBaseValue@PlanetData[celestialName,"PeriapsisArgument"],*)
(*GetSIBaseValue@PlanetData[celestialName,"AscendingNodeLongitude"],*)
(*GetSIBaseValue@PlanetData[celestialName,"Inclination"],*)
(*GetSIBaseValue@PlanetData[celestialName,"MeanAnomaly"]};*)
(*GetPlanetaryMoonData[celestialName_]:=*)
(*{celestialName,*)
(*PlanetaryMoonData[celestialName, "Color"],*)
(*GetSIBaseValue@PlanetaryMoonData[celestialName, "Radius"],*)
(*GetSIBaseValue@PlanetaryMoonData[celestialName,"Mass"]*GetSIBaseValue@"GravitationalConstant",*)
(*GetSIBaseValue@PlanetaryMoonData[celestialName,"SemimajorAxis"],*)
(*PlanetaryMoonData[celestialName,"Eccentricity"],*)
(*GetSIBaseValue@PlanetaryMoonData[celestialName,"PeriapsisArgument"],*)
(*GetSIBaseValue@PlanetaryMoonData[celestialName,"AscendingNodeLongitude"],*)
(*GetSIBaseValue@PlanetaryMoonData[celestialName,"Inclination"],*)
(*GetSIBaseValue@PlanetaryMoonData[celestialName,"EccentricAnomaly"]-PlanetaryMoonData[celestialName,"Eccentricity"]Sin[GetSIBaseValue@PlanetaryMoonData[celestialName,"EccentricAnomaly"]]};*)
(**)
(**)
(*EccentricAnomaly[ma_,e_,\[Epsilon]_,countMax_,ini_]:= *)
(*Module[*)
(*{xOld=ma+1000,x=ma,count=0,x1,x2},*)
(*While[Abs[x-xOld]>\[Epsilon]&& count<countMax,*)
(*xOld=x;*)
(*If[count<ini,*)
(*x1=ma+e*Sin@x; x2=ma+e*Sin@x1;x=(x1+x2)*0.5,*)
(*x+=(ma-x+e*Sin@x)/(1.-e*Cos@x)];*)
(*count++];*)
(*x];*)
(**)
(*KeplerianToCartesianFast[\[Mu]_,a_,e_,\[Omega]_,\[CapitalOmega]_,i_,M_,t_]:=*)
(*Module[*)
(*{Mt,EA,\[Nu],rct},*)
(*Mt=Mod[M+t Sqrt[\[Mu]/a^3],2Pi];*)
(*EA=EccentricAnomaly[Mt,e,10^-9,500,2];*)
(*\[Nu]=2ArcTan[Sqrt[(1+e)/(1-e)]Tan[0.5EA]]+2Pi;*)
(*rct=a(1-e Cos@EA);*)
(*{rct (Cos[\[Nu]+\[Omega]] Cos[\[CapitalOmega]]-Cos[i] Sin[\[Nu]+\[Omega]] Sin[\[CapitalOmega]]),*)
(*rct (Cos[i] Cos[\[CapitalOmega]] Sin[\[Nu]+\[Omega]]+Cos[\[Nu]+\[Omega]] Sin[\[CapitalOmega]]),*)
(*rct Sin[i] Sin[\[Nu]+\[Omega]]}];*)
